-
  name: copying file to managed nodes if conditions are true
  hosts: web
  tasks:
    - name: copy a file to web server
      copy:
        src: /tmp/new.txt
        dest: /tmp/
        owner: root
        group: root
        mode: 0777
      # when: (ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] == "7"
      when: ansible_facts["distribution"] == "CentOS" and ansible_facts["distribution_major_version"] == "7"
      # when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"
