-
  name: appache installation
  hosts: web
  tasks:
    - name: install appache
      yum:
        name: httpd
        state: present

    - name: check the state of appache all_server
      service:
        name: httpd
        state: started

    - name: remove appache httpd
      yum:
        name: httpd
        state: absent
