-
  name: using ansible_handler during appache installation
  hosts: web
  tasks:
    - name: installing appache web server
      yum:
        name: httpd
        state: latest

    - name: restaritng and enabling httpd service
      service:
          name: httpd
          state: restarted
          enabled: true

    - name: deliver the html content
      copy:
        src: /root/test.html
        dest: "/var/www/vhost/{{ ansible_hostname }}"
      notify:
        - restart_httpd_service


  handlers:
    - name: restart_httpd_service
      service:
        name: httpd
        state: restarted
